# Generated by Django 2.1.7 on 2019-03-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conte_title', models.CharField(max_length=200, verbose_name='故事标题')),
                ('conte_body', models.TextField(verbose_name='故事内容')),
            ],
            options={
                'verbose_name': '小故事',
                'verbose_name_plural': '小故事',
                'db_table': 'conte',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名')),
                ('product_img', models.ImageField(upload_to='static/img', verbose_name='产品图片')),
                ('product_price', models.FloatField(verbose_name='产品价格')),
                ('product_body', models.TextField(verbose_name='产品信息')),
            ],
            options={
                'verbose_name': '商品列表',
                'verbose_name_plural': '商品列表',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('promotion_body', models.TextField(verbose_name='活动内容')),
                ('promotion_img', models.ImageField(upload_to='static/img', verbose_name='活动图片')),
                ('product_rebate', models.FloatField(default=1.0, verbose_name='产品折扣')),
                ('promotion_product', models.ManyToManyField(related_name='product_list', to='beverageApp.Product', verbose_name='促销产品')),
            ],
            options={
                'verbose_name': '促销表',
                'verbose_name_plural': '促销表',
                'db_table': 'promotion',
            },
        ),
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200, verbose_name='属性名')),
            ],
            options={
                'verbose_name': '属性表',
                'verbose_name_plural': '属性表',
                'db_table': 'property_type',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Product', verbose_name='推荐产品')),
            ],
            options={
                'verbose_name': '推荐表',
                'verbose_name_plural': '推荐表',
                'db_table': 'recommend',
            },
        ),
        migrations.CreateModel(
            name='Reportforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='商品成交价格')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='购买商品的时间')),
                ('number', models.IntegerField(default=1, verbose_name='购买的数量')),
                ('state', models.IntegerField(choices=[('否', 0), ('是', 1)], default=0, verbose_name='成交状态')),
                ('proudect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Product', verbose_name='产品销售')),
            ],
            options={
                'verbose_name': '流水详情表',
                'verbose_name_plural': '流水详情表',
                'db_table': 'reportforms',
            },
        ),
        migrations.CreateModel(
            name='Season_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=200, verbose_name='季节名')),
            ],
            options={
                'verbose_name': '季节表',
                'verbose_name_plural': '季节表',
                'db_table': 'season_type',
            },
        ),
        migrations.CreateModel(
            name='Staple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staple_name', models.CharField(max_length=150, verbose_name='产品原料')),
                ('staple_price', models.FloatField(verbose_name='原料价格')),
            ],
            options={
                'verbose_name': '产品原料表',
                'verbose_name_plural': '产品原料表',
                'db_table': 'staple',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_staple_number', models.IntegerField(verbose_name='库存数量')),
                ('enter_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('stock_staple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staple', to='beverageApp.Staple', verbose_name='库存原料')),
            ],
            options={
                'verbose_name': '产品原料库存列表',
                'verbose_name_plural': '产品原料库存列表',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, verbose_name='类型名')),
                ('product_property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Property_type', verbose_name='产品属性')),
                ('product_season_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Season_type', verbose_name='季节分类')),
            ],
            options={
                'verbose_name': '产品类型',
                'verbose_name_plural': '产品类型',
                'db_table': 'type',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_staple',
            field=models.ManyToManyField(related_name='product_info', to='beverageApp.Staple', verbose_name='产品原料'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Type', verbose_name='产品类型'),
        ),
    ]
