# Generated by Django 2.1.7 on 2019-03-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beverageApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='客户名')),
                ('card_number', models.IntegerField(verbose_name='会员卡号')),
                ('card_password', models.CharField(max_length=100, verbose_name='卡号密码')),
                ('associator_rebate', models.FloatField(default=0.95, verbose_name='产品折扣')),
            ],
            options={
                'verbose_name': '会员表',
                'verbose_name_plural': '会员表',
                'db_table': 'Associator_Table',
            },
        ),
        migrations.CreateModel(
            name='CupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_size', models.IntegerField(choices=[(1, '大杯'), (2, '中杯'), (3, '小杯')], verbose_name='杯子大小')),
                ('price', models.FloatField(verbose_name='产品价格')),
                ('cup_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '杯子规格表',
                'verbose_name_plural': '杯子规格表',
                'db_table': 'Cup_Table',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200, verbose_name='用户名')),
                ('emp_password', models.CharField(max_length=200, verbose_name='用户密码')),
            ],
            options={
                'verbose_name': '店员表',
                'verbose_name_plural': '店员表',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='店员名')),
                ('tel', models.CharField(max_length=200, verbose_name='电话号码')),
                ('addr', models.CharField(max_length=200, verbose_name='家庭住址')),
                ('is_no', models.IntegerField(choices=[(1, '是'), (2, '否')], verbose_name='是否结婚')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Employee', verbose_name='关联店员')),
            ],
            options={
                'verbose_name': '店员详情表',
                'verbose_name_plural': '店员详情表',
                'db_table': 'Employee_detail',
            },
        ),
    ]
