# Generated by Django 2.1.7 on 2019-03-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beverageApp', '0002_associatortable_cuptable_employee_employeedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatortable',
            name='ass_rep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Reportforms', verbose_name='订单信息'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuptable',
            name='cup_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='beverageApp.Product', verbose_name='关联产品'),
        ),
    ]
