# Generated by Django 2.1.7 on 2019-03-23 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beverageApp', '0003_auto_20190322_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportforms',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beverageApp.Employee', verbose_name='员工'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associatortable',
            name='ass_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass_rep', to='beverageApp.Reportforms', verbose_name='订单信息'),
        ),
    ]
